### ISSUE TITLE
Find a Word List to pull words from

### ISSUE THREAD

**Issue by JakeBrand** [tdjohner/Word-Puzzle#5]
To start with, lets just grab a big list of words. We can expand it or trim it later.

**Comment by JakeBrand** [comment]
The first BIG one I saw:
https://github.com/dwyl/english-words
The downloaded text file is only 3.9MB (which is WAY smaller than I was expecting). Small enough that we could conceivable put the whole thing into our app no problem.
- Note: We have to read through the licensing and make sure we're using it appropriately.

**Comment by JakeBrand** [comment]
The text file as downloaded from https://github.com/dwyl/english-words:
[EnglishWords350k.txt](https://github.com/tdjohner/Word-Puzzle/files/428978/EnglishWords350k.txt)

**Comment by tdjohner** [comment]
from what I understood we're fine to use this file.
the relevant information was in the 'small print' clause of the 
https://github.com/tdjohner/english-words/blob/master/word_list_moby_README.txt

**Comment by tdjohner** [comment]
stripped all the apostrophe's and word's leaving only the four letter ones, committed it
